//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguro.Infraestructure.Repository.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        public int id { get; set; }
        public double amountInsured { get; set; }
        public string email { get; set; }
        public System.DateTime inceptionDate { get; set; }
        public bool installmentPayment { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
